---

- name: Prerequisites to k3s
  hosts: k3s_cluster
  gather_facts: yes
  become: yes
  roles:
  - role: prereq
  - role: raspberrypi
  - role: hostname
  - role: ansible-netplan

- name: Build a cluster with an HA control plane
  hosts: k3s_cluster
  become: yes
  any_errors_fatal: true
  roles:
  - role: k3s

- name: Make Kubeconfig accessible from outside the cluster
  hosts: master
  become: yes
  any_errors_fatal: true
  roles:
  - role: kubeconfig
