---
ansible_user: charles

# No custom params (for now) for the agents.
# k3s_agent:

k3s_state: installed # 'uninstalled' to uninstall k3s
k3s_github_url: https://github.com/k3s-io/k3s
k3s_release_version: v1.22.5+k3s1
k3s_etcd_datastore: true
k3s_become_for_all: true

# IP Address of the first master node.
k3s_registration_address: "{{ hostvars[groups['master'][0]]['ansible_host'] | default(groups['master'][0]) }}"

# k3s control-plane settings.
k3s_server:
  cluster-cidr: 10.42.0.0/16
  flannel-backend: 'vxlan'
  disable:
  - traefik
  - servicelb

  # etcd backups options
  #
  etcd-snapshot-schedule-cron: '0 2 * * *' # everyday at 2AM
  etcd-snapshot-retention: '7' # keep 7 backups in total (for a 7-day period)
  etcd-snapshot-dir: /var/lib/rancher/k3s/server/db/snapshots
  
  # etcd restore options
  #
  # cluster-reset:
  # cluster-reset-restore-path: /var/lib/rancher/k3s/server/db/snapshots/<SNAPSHOT_FILE_NAME>
