- name: Configure container runtime to use Nvidia GPU
  become: true
  ansible.builtin.command: nvidia-ctk runtime configure --runtime=containerd

- name: Restart k3s
  become: true
  ansible.builtin.systemd:
    name: k3s
    state: restarted

- name: Wait for k3s API server to be ready after restart
  become: true
  ansible.builtin.wait_for:
    port: 6443
    host: 127.0.0.1
    delay: 5
    timeout: 120
    state: started
