---

- name: Prerequisites to k3s
  hosts: k3s_cluster
  gather_facts: true
  become: true
  roles:
  - role: prereq

- name: Raspberry Pi configuration
  hosts: raspberrypi
  gather_facts: true
  become: true
  roles:
  - role: raspberrypi
  - role: hostname        # this is done manually for the amd64 hosts.
  - role: ansible-netplan # this is done manually for the amd64 hosts.

- name: NVIDIA Server configuration
  hosts: nvidiaserver
  gather_facts: true
  become: true
  roles:
  - role: nvidiaserver

- name: Ceph configuration
  hosts: ceph
  gather_facts: true
  become: true
  roles:
  - role: ceph

- name: Build a cluster with an HA control plane
  hosts: k3s_cluster
  become: true
  any_errors_fatal: true
  roles:
  - role: k3s

- name: Make Kubeconfig accessible from outside the cluster
  hosts: master
  become: true
  any_errors_fatal: true
  roles:
  - role: kubeconfig

- name: Post-installation steps for NVIDIA server
  hosts: nvidiaserver
  gather_facts: true
  become: true
  roles:
  - role: nvidiaserver-postinstall