---

- name: Prerequisites to k3s
  hosts: k3s_cluster
  gather_facts: true
  become: true
  roles:
  - role: prereq

- name: Raspberry Pi configuration
  hosts: raspberrypi
  gather_facts: true
  become: true
  roles:
  - role: raspberrypi
  - role: hostname        # this is done manually for the Intel NUC.
  - role: ansible-netplan # this is done manually for the Intel NUC.

- name: Media Server configuration
  hosts: mediaserver
  gather_facts: true
  become: true
  roles:
  - role: mediaserver

- name: Build a cluster with an HA control plane
  hosts: k3s_cluster
  become: true
  any_errors_fatal: true
  roles:
  - role: k3s

- name: Make Kubeconfig accessible from outside the cluster
  hosts: master
  become: true
  any_errors_fatal: true
  roles:
  - role: kubeconfig
