---

- name: Prerequisites to k3s
  hosts: k3s_cluster
  gather_facts: true
  become: true
  roles:
  - role: prereq

- name: Raspberry Pi configuration
  hosts: raspberrypi
  gather_facts: true
  become: true
  roles:
  - role: raspberrypi

- name: Networking configuration
  hosts: k3s_cluster
  gather_facts: true
  become: true
  roles:
  - role: hostname
  - role: ansible-netplan

- name: Build a cluster with an HA control plane
  hosts: k3s_cluster
  become: true
  any_errors_fatal: true
  roles:
  - role: k3s

- name: Make Kubeconfig accessible from outside the cluster
  hosts: master
  become: true
  any_errors_fatal: true
  roles:
  - role: kubeconfig
